# Generated by Django 4.2.10 on 2024-03-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_feedback_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminreply',
            options={'verbose_name': 'Admin Reply', 'verbose_name_plural': 'Admin Replies'},
        ),
    ]
