# Generated by Django 4.2.10 on 2024-03-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('exam_id', models.CharField(max_length=10)),
                ('question_id', models.CharField(max_length=10)),
                ('answer', models.CharField(default='N', max_length=1)),
            ],
        ),
    ]
