# Generated by Django 4.2.10 on 2024-03-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_text', 'exam')},
        ),
    ]
