# Generated by Django 4.2.10 on 2024-03-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_student_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('branch_name', 'college')},
        ),
    ]
