# Generated by Django 4.2.10 on 2024-03-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_branch_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_id',
            field=models.IntegerField(default=1),
        ),
    ]
