# Generated by Django 4.2.10 on 2024-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_enrollment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='answer',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
