# Generated by Django 4.2.10 on 2024-03-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_record_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
